inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 3.1

Gemspec/RequiredRubyVersion:
  Enabled: false

Style/GlobalVars:
  Exclude:
    - 'spec/**/*.rb'

Style/Documentation:
  Enabled: false

Naming/ConstantName:
  Enabled: false

Lint/SuppressedException:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/ParameterLists:
  CountKeywordArgs: false

Metrics/MethodLength:
  Max: 20
  Exclude:
    - 'spec/doubles/*.rb'

Metrics/ClassLength:
  Max: 200
  Exclude:
    - 'spec/**/*.rb'

Metrics/LineLength:
  Max: 100
  Exclude:
    - 'spec/**/*.rb'
